In [ ]:
!conda install numpy scipy scikit-learn pandas joblib pytorch
!pip install deap update_checker tqdm stopit xgboost
!pip install tpot

Retrieving notices: ...working... done
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ai/miniconda3

  added / updated specs:
    - joblib
    - numpy
    - pandas
    - pytorch
    - scikit-learn
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _sysroot_linux-64_curr_repodata_hack-3|      haa98f57_10          12 KB
    binutils_impl_linux-64-2.38|       h2a08ee3_1         5.2 MB
    binutils_linux-64-2.38.0   |       hc2dff05_0          24 KB
    blas-1.0                   |         openblas          46 KB
    bottleneck-1.3.7           |  py311hf4808d0_0         145 KB
    certifi-2024.8.30          |  py311h06a4308_0         163 KB
    cudatoolkit-11.8.0         |       h6a678d5_0       630.7 MB
    cudnn-8.9.2.26             |         cuda11_0       469.4 MB
    cupti-11.8.0               |       he078b1a_0        18.9 MB
    filelock-3.13.1            |  py311h06a4308_0          24 KB
    fsspec-2024.6.1            |  py311h06a4308_0         383 KB
    gcc_impl_linux-64-11.2.0   |       h1234567_1        22.2 MB
    gcc_linux-64-11.2.0        |       h5c386dc_0          25 KB
    gmp-6.2.1                  |       h295c915_3         544 KB
    gmpy2-2.1.2                |  py311hc9b5ff0_0         191 KB
    gxx_impl_linux-64-11.2.0   |       h1234567_1        10.6 MB
    gxx_linux-64-11.2.0        |       hc2dff05_0          24 KB
    intel-openmp-2023.1.0      |   hdb19cb5_46306        17.2 MB
    joblib-1.4.2               |  py311h06a4308_0         530 KB
    kernel-headers_linux-64-3.10.0|      h57e8cba_10         952 KB
    libgcc-devel_linux-64-11.2.0|       h1234567_1         2.5 MB
    libgfortran-ng-11.2.0      |       h00389a5_1          20 KB
    libgfortran5-11.2.0        |       h1234567_1         2.0 MB
    libopenblas-0.3.21         |       h043d6bf_0         5.4 MB
    libprotobuf-3.20.3         |       he621ea3_0         2.4 MB
    libstdcxx-devel_linux-64-11.2.0|       h1234567_1        14.6 MB
    magma-2.7.1                |       h2c23e93_0       104.8 MB
    mkl-2023.1.0               |   h213fc3f_46344       171.5 MB
    mpc-1.1.0                  |       h10f8cd9_1          90 KB
    mpfr-4.0.2                 |       hb69a4c5_1         487 KB
    mpmath-1.3.0               |  py311h06a4308_0         1.0 MB
    networkx-3.3               |  py311h06a4308_0         3.1 MB
    numexpr-2.8.7              |  py311h812550d_0         167 KB
    numpy-1.26.4               |  py311h24aa872_0          10 KB
    numpy-base-1.26.4          |  py311hbfb1bba_0         8.3 MB
    pandas-2.2.2               |  py311ha02d727_0        15.7 MB
    python-tzdata-2023.3       |     pyhd3eb1b0_0         140 KB
    pytorch-2.3.0              |gpu_cuda118py311h6b76543_100       561.9 MB
    scikit-learn-1.5.1         |  py311ha02d727_0        10.4 MB
    scipy-1.13.1               |  py311h24aa872_0        23.9 MB
    sympy-1.13.2               |  py311h06a4308_0        15.4 MB
    sysroot_linux-64-2.17      |      h57e8cba_10        32.6 MB
    tbb-2021.8.0               |       hdb19cb5_0         1.6 MB
    threadpoolctl-3.5.0        |  py311h92b7b1e_0          50 KB
    torchtriton-2.3.0          |cuda123py311hdb19cb5_0       120.6 MB
    ------------------------------------------------------------
                                           Total:        2.22 GB

The following NEW packages will be INSTALLED:

  _sysroot_linux-64~ pkgs/main/noarch::_sysroot_linux-64_curr_repodata_hack-3-haa98f57_10
  binutils_impl_lin~ pkgs/main/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1
  binutils_linux-64  pkgs/main/linux-64::binutils_linux-64-2.38.0-hc2dff05_0
  blas               pkgs/main/linux-64::blas-1.0-openblas
  bottleneck         pkgs/main/linux-64::bottleneck-1.3.7-py311hf4808d0_0
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-11.8.0-h6a678d5_0
  cudnn              pkgs/main/linux-64::cudnn-8.9.2.26-cuda11_0
  cupti              pkgs/main/linux-64::cupti-11.8.0-he078b1a_0
  filelock           pkgs/main/linux-64::filelock-3.13.1-py311h06a4308_0
  fsspec             pkgs/main/linux-64::fsspec-2024.6.1-py311h06a4308_0
  gcc_impl_linux-64  pkgs/main/linux-64::gcc_impl_linux-64-11.2.0-h1234567_1
  gcc_linux-64       pkgs/main/linux-64::gcc_linux-64-11.2.0-h5c386dc_0
  gmp                pkgs/main/linux-64::gmp-6.2.1-h295c915_3
  gmpy2              pkgs/main/linux-64::gmpy2-2.1.2-py311hc9b5ff0_0
  gxx_impl_linux-64  pkgs/main/linux-64::gxx_impl_linux-64-11.2.0-h1234567_1
  gxx_linux-64       pkgs/main/linux-64::gxx_linux-64-11.2.0-hc2dff05_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2023.1.0-hdb19cb5_46306
  joblib             pkgs/main/linux-64::joblib-1.4.2-py311h06a4308_0
  kernel-headers_li~ pkgs/main/noarch::kernel-headers_linux-64-3.10.0-h57e8cba_10
  libgcc-devel_linu~ pkgs/main/linux-64::libgcc-devel_linux-64-11.2.0-h1234567_1
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-11.2.0-h00389a5_1
  libgfortran5       pkgs/main/linux-64::libgfortran5-11.2.0-h1234567_1
  libopenblas        pkgs/main/linux-64::libopenblas-0.3.21-h043d6bf_0
  libprotobuf        pkgs/main/linux-64::libprotobuf-3.20.3-he621ea3_0
  libstdcxx-devel_l~ pkgs/main/linux-64::libstdcxx-devel_linux-64-11.2.0-h1234567_1
  magma              pkgs/main/linux-64::magma-2.7.1-h2c23e93_0
  mkl                pkgs/main/linux-64::mkl-2023.1.0-h213fc3f_46344
  mpc                pkgs/main/linux-64::mpc-1.1.0-h10f8cd9_1
  mpfr               pkgs/main/linux-64::mpfr-4.0.2-hb69a4c5_1
  mpmath             pkgs/main/linux-64::mpmath-1.3.0-py311h06a4308_0
  networkx           pkgs/main/linux-64::networkx-3.3-py311h06a4308_0
  numexpr            pkgs/main/linux-64::numexpr-2.8.7-py311h812550d_0
  numpy              pkgs/main/linux-64::numpy-1.26.4-py311h24aa872_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.26.4-py311hbfb1bba_0
  pandas             pkgs/main/linux-64::pandas-2.2.2-py311ha02d727_0
  python-tzdata      pkgs/main/noarch::python-tzdata-2023.3-pyhd3eb1b0_0
  pytorch            pkgs/main/linux-64::pytorch-2.3.0-gpu_cuda118py311h6b76543_100
  scikit-learn       pkgs/main/linux-64::scikit-learn-1.5.1-py311ha02d727_0
  scipy              pkgs/main/linux-64::scipy-1.13.1-py311h24aa872_0
  sympy              pkgs/main/linux-64::sympy-1.13.2-py311h06a4308_0
  sysroot_linux-64   pkgs/main/noarch::sysroot_linux-64-2.17-h57e8cba_10
  tbb                pkgs/main/linux-64::tbb-2021.8.0-hdb19cb5_0
  threadpoolctl      pkgs/main/linux-64::threadpoolctl-3.5.0-py311h92b7b1e_0
  torchtriton        pkgs/main/linux-64::torchtriton-2.3.0-cuda123py311hdb19cb5_0

The following packages will be UPDATED:

  certifi                          2024.7.4-py311h06a4308_0 --> 2024.8.30-py311h06a4308_0


Proceed ([y]/n)?

In [172]:
import pandas as pd
import numpy as np
from autogluon.tabular import TabularDataset, TabularPredictor
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, PolynomialFeatures
import autogluon.eda.auto as auto

ModuleNotFoundError: No module named 'autogluon.eda'

In [3]:
odroid1 = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/odroid1_firefox_carbonyl7.csv")
odroid2 = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/odroid2_firefox_carbonyl7.csv")
odroid3 = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/odroid3_firefox_carbonyl7.csv")
odroid4 = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/odroid4_firefox_carbonyl7.csv")

In [4]:
rpi4a = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/rpi-4a_chrome_carbonyl7.csv")
rpi8a = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/rpi-8a_chrome_carbonyl7.csv")
rpi8b = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/rpi_8b_carbonyl_onscreen.csv")
rpi8c = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/rpi_8c_carbonyl_onscreen.csv")
rpi8d = pd.read_csv("https://raw.githubusercontent.com/brite3001/drawnapart/master/carbonyl/vec_7/rpi-8d_chrome_carbonyl7.csv")

In [190]:
df = pd.concat([odroid1[:1000], odroid2[:1000], odroid3[:1000], odroid4[:1000], rpi4a[:1000], rpi8a[:1000], rpi8b[:1000], rpi8c[:1000], rpi8d[:1000]])
df = df.sample(frac=1).reset_index(drop=True)

In [191]:
df.head()

,label,Feature 0,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6
0,rpi_8c,63.9,67.3,61.6,60.0,59.7,59.9,59.8
1,rpi-8d,64.3,60.9,60.8,60.1,59.5,59.5,59.3
2,odroid1,88.0,85.6,85.4,84.3,83.7,84.0,83.9
3,rpi-8d,63.5,61.9,60.6,59.4,59.4,59.2,59.3
4,rpi_8c,63.1,61.8,61.7,60.1,60.4,60.7,60.4

In [192]:
len(df)

9000

In [193]:
# scaler = MinMaxScaler()
# df.iloc[:, 1:] = scaler.fit_transform(df.iloc[:, 1:])

In [194]:
df.head()

,label,Feature 0,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6
0,rpi_8c,63.9,67.3,61.6,60.0,59.7,59.9,59.8
1,rpi-8d,64.3,60.9,60.8,60.1,59.5,59.5,59.3
2,odroid1,88.0,85.6,85.4,84.3,83.7,84.0,83.9
3,rpi-8d,63.5,61.9,60.6,59.4,59.4,59.2,59.3
4,rpi_8c,63.1,61.8,61.7,60.1,60.4,60.7,60.4

In [195]:
i = 8000

train_data = df.head(i)
test_data = df.tail(1000)

predictor = TabularPredictor(label='label').fit(train_data, num_gpus=1, presets='medium_quality')
y_pred = predictor.predict(test_data)
y_pred_proba = predictor.predict_proba(test_data)
results = predictor.evaluate(test_data, detailed_report=True)

model_leaderboard = predictor.leaderboard(test_data)

feature_importance = predictor.feature_importance(test_data)

No path specified. Models will be saved in: "AutogluonModels/ag-20240911_060003"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.11.9
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15)
CPU Count:          12
Memory Avail:       12.59 GB / 15.86 GB (79.4%)
Disk Space Avail:   4.39 GB / 96.93 GB (4.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20240911_060003"
Train Data Rows:    8000
Train Data Columns: 7
Label Column:       label
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == object).
	9 unique label values:  ['rpi_8c', 'rpi-8d', 'odroid1', 'odroid2', 'rpi-4a', 'rpi-8a', 'odroid3', 'rpi_8b', 'odroid4']
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 9
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12896.36 MB
	Train Data (Original)  Memory Usage: 0.43 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 7 | ['Feature 0', 'Feature 1', 'Feature 2', 'Feature 3', 'Feature 4', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 7 | ['Feature 0', 'Feature 1', 'Feature 2', 'Feature 3', 'Feature 4', ...]
	0.0s = Fit runtime
	7 features in original data used to generate 7 features in processed data.
	Train Data (Processed) Memory Usage: 0.43 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 7200, Val Rows: 800
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.6575	 = Validation score   (accuracy)
	0.0s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.6438	 = Validation score   (accuracy)
	0.0s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.6488	 = Validation score   (accuracy)
	2.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...
	Training LightGBMXT with GPU, note that this may negatively impact model quality compared to CPU training.
	0.7188	 = Validation score   (accuracy)
	1.86s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Training LightGBM with GPU, note that this may negatively impact model quality compared to CPU training.
	0.7025	 = Validation score   (accuracy)
	3.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7025	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.6963	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.7175	 = Validation score   (accuracy)
	1.14s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.6987	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.6937	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: XGBoost ...
/home/ai/miniconda3/lib/python3.11/site-packages/xgboost/core.py:160: UserWarning: [16:00:15] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/home/ai/miniconda3/lib/python3.11/site-packages/xgboost/core.py:160: UserWarning: [16:00:17] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
	0.7013	 = Validation score   (accuracy)
	2.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.6825	 = Validation score   (accuracy)
	7.82s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Training LightGBMLarge with GPU, note that this may negatively impact model quality compared to CPU training.
	0.7	 = Validation score   (accuracy)
	30.51s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'CatBoost': 0.5, 'LightGBMXT': 0.333, 'NeuralNetFastAI': 0.083, 'LightGBM': 0.083}
	0.7288	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 52.44s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 97031.4 rows/s (800 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240911_060003")
Computing feature importance via permutation shuffling for 7 features using 1000 rows with 5 shuffle sets...
	0.66s	= Expected runtime (0.13s per shuffle set)
	0.29s	= Actual runtime (Completed 5 of 5 shuffle sets)

In [196]:
stats_df

   data_amount  precision  recall        f1
0         8000   0.685685   0.696  0.688379

In [197]:
model_leaderboard

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.731,0.72875,accuracy,0.026523,0.008245,8.778381,0.004663,0.000277,0.049092,2,True,14
1,ExtraTreesEntr,0.723,0.69375,accuracy,0.123631,0.032603,0.478891,0.123631,0.032603,0.478891,1,True,10
2,RandomForestEntr,0.722,0.69625,accuracy,0.095694,0.043351,0.470940,0.095694,0.043351,0.470940,1,True,7
3,CatBoost,0.717,0.71750,accuracy,0.007531,0.000823,1.135368,0.007531,0.000823,1.135368,1,True,8
4,LightGBMXT,0.715,0.71875,accuracy,0.004081,0.002031,1.858227,0.004081,0.002031,1.858227,1,True,4
5,LightGBM,0.714,0.70250,accuracy,0.001631,0.000563,3.604902,0.001631,0.000563,3.604902,1,True,5
6,ExtraTreesGini,0.714,0.69875,accuracy,0.102725,0.033184,0.468033,0.102725,0.033184,0.468033,1,True,9
7,RandomForestGini,0.707,0.70250,accuracy,0.061839,0.033341,0.463443,0.061839,0.033341,0.463443,1,True,6
8,XGBoost,0.706,0.70125,accuracy,0.029412,0.002495,2.418061,0.029412,0.002495,2.418061,1,True,11
9,LightGBMLarge,0.697,0.70000,accuracy,0.064624,0.018964,30.511457,0.064624,0.018964,30.511457,1,True,13
10,NeuralNetFastAI,0.671,0.64875,accuracy,0.008617,0.004551,2.130791,0.008617,0.004551,2.130791,1,True,3
11,NeuralNetTorch,0.665,0.68250,accuracy,0.010481,0.002221,7.822980,0.010481,0.002221,7.822980,1,True,12
12,KNeighborsUnif,0.657,0.65750,accuracy,0.012740,0.012295,0.003899,0.012740,0.012295,0.003899,1,True,1
13,KNeighborsDist,0.656,0.64375,accuracy,0.012985,0.012113,0.003830,0.012985,0.012113,0.003830,1,True,2

In [198]:
feature_importance

           importance    stddev       p_value  n  p99_high   p99_low
Feature 1      0.1152  0.004025  1.785233e-07  5  0.123487  0.106913
Feature 3      0.0870  0.008515  1.087061e-05  5  0.104532  0.069468
Feature 2      0.0648  0.008349  3.234414e-05  5  0.081990  0.047610
Feature 5      0.0560  0.005701  1.271213e-05  5  0.067738  0.044262
Feature 6      0.0548  0.006058  1.763386e-05  5  0.067274  0.042326
Feature 0      0.0298  0.008379  6.769363e-04  5  0.047052  0.012548
Feature 4      0.0286  0.008295  7.615403e-04  5  0.045679  0.011521